spring.application.name=hangangactivity

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.web.resources.static-locations=classpath:/static/
spring.resources.static-locations=classpath:/static/


#spring.datasource.url=jdbc:postgresql://db:5432/mydatabase
#spring.datasource.username=myuser
#spring.datasource.password=mypassword
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
